# -*- coding: utf-8 -*-
"""Branching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12R3UX_-wUqPEZ7cCXeRXMAHQGilZLSnX

### Branching

In questo notebook faremo delle prove di branching con un repository di nome `primoBranch`. Mettiamo prima le celle di tipo "utility" per inizializzare o cancellare/ripristinare l'ambiente.
"""

# 0. cella per il ripristino dell'ambiente;
# % cd
# % rm -rf primoBranch

# 1. Passo configurazione dell'utente
# %%bash
git config --global user.name "imlored"
git config --global user.email "burduja.loredana@liceomorin.net"
git config --list

# 3. costruisci una directory di nome `primoBranch`, entraci e inizializza il repository;
# % mkdir primoBranch
# % cd primoBranch
# create a new git repository:
! git init

# 4. modifica del repository
! echo "# Prova di brancing" > README.md
! echo "### 1. Versione Principale" >> README.md
! echo "1." > file1.txt
! git add README.md file1.txt
! git commit -m "Prima modifica nel master"

# 5. lista commit
! git shortlog

# 6. costruzione di un branch e modifica del repository (nella parte branch)
! git checkout -b ver2
! echo "### Versione branch" >> README.md
! echo "2." >> file1.txt
! git add README.md file1.txt
! git commit -m "Prima modifica nel brach"

# 7. lista commit
! git shortlog

# 8. modifica al master
! git checkout master
! cat README.md
! echo -----------------------------------------
! cat file1.txt
! echo "### Altra modifica nel master" >> README.md
! echo "3." >> file1.txt
! git add README.md file1.txt
! git commit -m "Seconda modifica nel master"

# 9. modifica al branch
! git checkout ver2
! cat README.md
! echo -----------------------------------------
! cat file1.txt
! echo "### Altra modifica nel branch" >> README.md
! echo "4." >> file1.txt
! git add README.md file1.txt
! git commit -m "Seconda modifica nel branch"

# 10. lista commit
! git shortlog

# 11. rappresentazione grafica di TUTTI i commit effettuati
from IPython.display import Image
Image(url='https://raw.githubusercontent.com/sdoro/images/master/git/branching.png')

"""### Esercizio di riflessione sulla gestione delle versioni

Rispondere alle seguenti domande (e riportare su classroom):
1. al passo 9 prima del commit che cosa contiene il file `file1.txt` ? e dopo il run della cella?
2. al passo 8 prima del commit che cosa contiene il file `file1.txt` ? e dopo il run della cella?
3. al passo 6 prima del commit che cosa contiene il file `file1.txt` ? e dopo il run della cella?
4. al termine del passo 9 che cosa contiene il file `README.md` ?
5. al termine del passo 8 che cosa contiene il file `README.md` ?
"""